DROP TABLE CLOUDMAP2;
DROP TABLE CLOUDMAP_USERS;

CREATE TABLE CLOUDMAP_USERS (
  USERID VARCHAR(25) PRIMARY KEY
);

CREATE TABLE CLOUDMAP2 (
  KEY VARCHAR(255),
  VALUE BLOB,
  VERSION INTEGER DEFAULT 0,
  USERID VARCHAR(25) NOT NULL REFERENCES CLOUDMAP_USERS,
  CONSTRAINT PK_CLOUDMAP PRIMARY KEY(KEY,USERID)
);


INSERT INTO CLOUDMAP_USERS VALUES ('test-user100');
INSERT INTO CLOUDMAP_USERS VALUES ('test-user200');